[build]
  publish = "client/build" # Путь к папке сборки клиентской части
  command = "npm run build" # Команда для сборки клиентской части

[[redirects]]
  from = "/api" # Перенаправление всех запросов, начинающихся с /api/ на ваш сервер
  to = "http://localhost:3000" # Замените на адрес вашего сервера
  status = 200
